/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestUploadRouteImport } from './routes/test-upload'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoPrismaRouteImport } from './routes/demo/prisma'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppFamilyRouteImport } from './routes/app/family'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as ApiUploadIndexRouteImport } from './routes/api/upload/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as AppProfileViewRouteImport } from './routes/app/profile/view'
import { Route as AppProfileEditRouteImport } from './routes/app/profile/edit'
import { Route as AppFamilyEditRouteImport } from './routes/app/family/edit'
import { Route as AppFamilyDashboardRouteImport } from './routes/app/family/dashboard'
import { Route as AppFamilyAddRouteImport } from './routes/app/family/add'
import { Route as ApiFileKeyRouteImport } from './routes/api/file/$key'
import { Route as ApiFileSplatRouteImport } from './routes/api/file/$'
import { Route as ApiFamilySearchRouteImport } from './routes/api/family/search'
import { Route as ApiFamilySplatRouteImport } from './routes/api/family/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const TestUploadRoute = TestUploadRouteImport.update({
  id: '/test-upload',
  path: '/test-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPrismaRoute = DemoPrismaRouteImport.update({
  id: '/demo/prisma',
  path: '/demo/prisma',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppFamilyRoute = AppFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const ApiUploadIndexRoute = ApiUploadIndexRouteImport.update({
  id: '/api/upload/',
  path: '/api/upload/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileViewRoute = AppProfileViewRouteImport.update({
  id: '/view',
  path: '/view',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppProfileEditRoute = AppProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppFamilyEditRoute = AppFamilyEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppFamilyRoute,
} as any)
const AppFamilyDashboardRoute = AppFamilyDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppFamilyRoute,
} as any)
const AppFamilyAddRoute = AppFamilyAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppFamilyRoute,
} as any)
const ApiFileKeyRoute = ApiFileKeyRouteImport.update({
  id: '/api/file/$key',
  path: '/api/file/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileSplatRoute = ApiFileSplatRouteImport.update({
  id: '/api/file/$',
  path: '/api/file/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFamilySearchRoute = ApiFamilySearchRouteImport.update({
  id: '/api/family/search',
  path: '/api/family/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFamilySplatRoute = ApiFamilySplatRouteImport.update({
  id: '/api/family/$',
  path: '/api/family/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/test-upload': typeof TestUploadRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/family': typeof AppFamilyRouteWithChildren
  '/app/profile': typeof AppProfileRouteWithChildren
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/family/$': typeof ApiFamilySplatRoute
  '/api/family/search': typeof ApiFamilySearchRoute
  '/api/file/$': typeof ApiFileSplatRoute
  '/api/file/$key': typeof ApiFileKeyRoute
  '/app/family/add': typeof AppFamilyAddRoute
  '/app/family/dashboard': typeof AppFamilyDashboardRoute
  '/app/family/edit': typeof AppFamilyEditRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/profile/view': typeof AppProfileViewRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/upload': typeof ApiUploadIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/test-upload': typeof TestUploadRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/family': typeof AppFamilyRouteWithChildren
  '/app/profile': typeof AppProfileRouteWithChildren
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/family/$': typeof ApiFamilySplatRoute
  '/api/family/search': typeof ApiFamilySearchRoute
  '/api/file/$': typeof ApiFileSplatRoute
  '/api/file/$key': typeof ApiFileKeyRoute
  '/app/family/add': typeof AppFamilyAddRoute
  '/app/family/dashboard': typeof AppFamilyDashboardRoute
  '/app/family/edit': typeof AppFamilyEditRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/profile/view': typeof AppProfileViewRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/upload': typeof ApiUploadIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/test-upload': typeof TestUploadRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/family': typeof AppFamilyRouteWithChildren
  '/app/profile': typeof AppProfileRouteWithChildren
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/family/$': typeof ApiFamilySplatRoute
  '/api/family/search': typeof ApiFamilySearchRoute
  '/api/file/$': typeof ApiFileSplatRoute
  '/api/file/$key': typeof ApiFileKeyRoute
  '/app/family/add': typeof AppFamilyAddRoute
  '/app/family/dashboard': typeof AppFamilyDashboardRoute
  '/app/family/edit': typeof AppFamilyEditRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/profile/view': typeof AppProfileViewRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/upload/': typeof ApiUploadIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/test-upload'
    | '/app/dashboard'
    | '/app/family'
    | '/app/profile'
    | '/demo/prisma'
    | '/demo/tanstack-query'
    | '/api/auth/$'
    | '/api/family/$'
    | '/api/family/search'
    | '/api/file/$'
    | '/api/file/$key'
    | '/app/family/add'
    | '/app/family/dashboard'
    | '/app/family/edit'
    | '/app/profile/edit'
    | '/app/profile/view'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/upload'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/test-upload'
    | '/app/dashboard'
    | '/app/family'
    | '/app/profile'
    | '/demo/prisma'
    | '/demo/tanstack-query'
    | '/api/auth/$'
    | '/api/family/$'
    | '/api/family/search'
    | '/api/file/$'
    | '/api/file/$key'
    | '/app/family/add'
    | '/app/family/dashboard'
    | '/app/family/edit'
    | '/app/profile/edit'
    | '/app/profile/view'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/upload'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/test-upload'
    | '/app/dashboard'
    | '/app/family'
    | '/app/profile'
    | '/demo/prisma'
    | '/demo/tanstack-query'
    | '/api/auth/$'
    | '/api/family/$'
    | '/api/family/search'
    | '/api/file/$'
    | '/api/file/$key'
    | '/app/family/add'
    | '/app/family/dashboard'
    | '/app/family/edit'
    | '/app/profile/edit'
    | '/app/profile/view'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/upload/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  TestUploadRoute: typeof TestUploadRoute
  DemoPrismaRoute: typeof DemoPrismaRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFamilySplatRoute: typeof ApiFamilySplatRoute
  ApiFamilySearchRoute: typeof ApiFamilySearchRoute
  ApiFileSplatRoute: typeof ApiFileSplatRoute
  ApiFileKeyRoute: typeof ApiFileKeyRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  ApiUploadIndexRoute: typeof ApiUploadIndexRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-upload': {
      id: '/test-upload'
      path: '/test-upload'
      fullPath: '/test-upload'
      preLoaderRoute: typeof TestUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/prisma': {
      id: '/demo/prisma'
      path: '/demo/prisma'
      fullPath: '/demo/prisma'
      preLoaderRoute: typeof DemoPrismaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/family': {
      id: '/app/family'
      path: '/family'
      fullPath: '/app/family'
      preLoaderRoute: typeof AppFamilyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/upload/': {
      id: '/api/upload/'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile/view': {
      id: '/app/profile/view'
      path: '/view'
      fullPath: '/app/profile/view'
      preLoaderRoute: typeof AppProfileViewRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/app/profile/edit': {
      id: '/app/profile/edit'
      path: '/edit'
      fullPath: '/app/profile/edit'
      preLoaderRoute: typeof AppProfileEditRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/app/family/edit': {
      id: '/app/family/edit'
      path: '/edit'
      fullPath: '/app/family/edit'
      preLoaderRoute: typeof AppFamilyEditRouteImport
      parentRoute: typeof AppFamilyRoute
    }
    '/app/family/dashboard': {
      id: '/app/family/dashboard'
      path: '/dashboard'
      fullPath: '/app/family/dashboard'
      preLoaderRoute: typeof AppFamilyDashboardRouteImport
      parentRoute: typeof AppFamilyRoute
    }
    '/app/family/add': {
      id: '/app/family/add'
      path: '/add'
      fullPath: '/app/family/add'
      preLoaderRoute: typeof AppFamilyAddRouteImport
      parentRoute: typeof AppFamilyRoute
    }
    '/api/file/$key': {
      id: '/api/file/$key'
      path: '/api/file/$key'
      fullPath: '/api/file/$key'
      preLoaderRoute: typeof ApiFileKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file/$': {
      id: '/api/file/$'
      path: '/api/file/$'
      fullPath: '/api/file/$'
      preLoaderRoute: typeof ApiFileSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/family/search': {
      id: '/api/family/search'
      path: '/api/family/search'
      fullPath: '/api/family/search'
      preLoaderRoute: typeof ApiFamilySearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/family/$': {
      id: '/api/family/$'
      path: '/api/family/$'
      fullPath: '/api/family/$'
      preLoaderRoute: typeof ApiFamilySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppFamilyRouteChildren {
  AppFamilyAddRoute: typeof AppFamilyAddRoute
  AppFamilyDashboardRoute: typeof AppFamilyDashboardRoute
  AppFamilyEditRoute: typeof AppFamilyEditRoute
}

const AppFamilyRouteChildren: AppFamilyRouteChildren = {
  AppFamilyAddRoute: AppFamilyAddRoute,
  AppFamilyDashboardRoute: AppFamilyDashboardRoute,
  AppFamilyEditRoute: AppFamilyEditRoute,
}

const AppFamilyRouteWithChildren = AppFamilyRoute._addFileChildren(
  AppFamilyRouteChildren,
)

interface AppProfileRouteChildren {
  AppProfileEditRoute: typeof AppProfileEditRoute
  AppProfileViewRoute: typeof AppProfileViewRoute
}

const AppProfileRouteChildren: AppProfileRouteChildren = {
  AppProfileEditRoute: AppProfileEditRoute,
  AppProfileViewRoute: AppProfileViewRoute,
}

const AppProfileRouteWithChildren = AppProfileRoute._addFileChildren(
  AppProfileRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppFamilyRoute: typeof AppFamilyRouteWithChildren
  AppProfileRoute: typeof AppProfileRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppFamilyRoute: AppFamilyRouteWithChildren,
  AppProfileRoute: AppProfileRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  TestUploadRoute: TestUploadRoute,
  DemoPrismaRoute: DemoPrismaRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFamilySplatRoute: ApiFamilySplatRoute,
  ApiFamilySearchRoute: ApiFamilySearchRoute,
  ApiFileSplatRoute: ApiFileSplatRoute,
  ApiFileKeyRoute: ApiFileKeyRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  ApiUploadIndexRoute: ApiUploadIndexRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
