/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestUploadRouteImport } from './routes/test-upload'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppProfileIndexRouteImport } from './routes/app/profile/index'
import { Route as AppFamilyIndexRouteImport } from './routes/app/family/index'
import { Route as AppAssetsIndexRouteImport } from './routes/app/assets/index'
import { Route as AppAgreementIndexRouteImport } from './routes/app/agreement/index'
import { Route as ApiUploadIndexRouteImport } from './routes/api/upload/index'
import { Route as AppProfileViewRouteImport } from './routes/app/profile/view'
import { Route as AppProfileEditRouteImport } from './routes/app/profile/edit'
import { Route as AppFamilyViewRouteImport } from './routes/app/family/view'
import { Route as AppFamilyEditRouteImport } from './routes/app/family/edit'
import { Route as AppFamilyAddRouteImport } from './routes/app/family/add'
import { Route as AppAssetsAddRouteImport } from './routes/app/assets/add'
import { Route as AppAgreementCreateRouteImport } from './routes/app/agreement/create'
import { Route as ApiFileKeyRouteImport } from './routes/api/file/$key'
import { Route as ApiFileSplatRouteImport } from './routes/api/file/$'
import { Route as ApiFamilySearchRouteImport } from './routes/api/family/search'
import { Route as ApiFamilySplatRouteImport } from './routes/api/family/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAssetSplatRouteImport } from './routes/api/asset/$'
import { Route as AppAssetsViewIndexRouteImport } from './routes/app/assets/view/index'
import { Route as AppAssetsEditIndexRouteImport } from './routes/app/assets/edit/index'
import { Route as AppAgreementViewIndexRouteImport } from './routes/app/agreement/view/index'
import { Route as AppAssetsViewIdRouteImport } from './routes/app/assets/view/$id'
import { Route as AppAssetsEditIdRouteImport } from './routes/app/assets/edit/$id'
import { Route as AppAgreementViewIdRouteImport } from './routes/app/agreement/view/$id'
import { Route as ApiUserProfileSplatRouteImport } from './routes/api/user/profile/$'

const TestUploadRoute = TestUploadRouteImport.update({
  id: '/test-upload',
  path: '/test-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)
const AppFamilyIndexRoute = AppFamilyIndexRouteImport.update({
  id: '/family/',
  path: '/family/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsIndexRoute = AppAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgreementIndexRoute = AppAgreementIndexRouteImport.update({
  id: '/agreement/',
  path: '/agreement/',
  getParentRoute: () => AppRoute,
} as any)
const ApiUploadIndexRoute = ApiUploadIndexRouteImport.update({
  id: '/api/upload/',
  path: '/api/upload/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileViewRoute = AppProfileViewRouteImport.update({
  id: '/profile/view',
  path: '/profile/view',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileEditRoute = AppProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppFamilyViewRoute = AppFamilyViewRouteImport.update({
  id: '/family/view',
  path: '/family/view',
  getParentRoute: () => AppRoute,
} as any)
const AppFamilyEditRoute = AppFamilyEditRouteImport.update({
  id: '/family/edit',
  path: '/family/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppFamilyAddRoute = AppFamilyAddRouteImport.update({
  id: '/family/add',
  path: '/family/add',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsAddRoute = AppAssetsAddRouteImport.update({
  id: '/assets/add',
  path: '/assets/add',
  getParentRoute: () => AppRoute,
} as any)
const AppAgreementCreateRoute = AppAgreementCreateRouteImport.update({
  id: '/agreement/create',
  path: '/agreement/create',
  getParentRoute: () => AppRoute,
} as any)
const ApiFileKeyRoute = ApiFileKeyRouteImport.update({
  id: '/api/file/$key',
  path: '/api/file/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileSplatRoute = ApiFileSplatRouteImport.update({
  id: '/api/file/$',
  path: '/api/file/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFamilySearchRoute = ApiFamilySearchRouteImport.update({
  id: '/api/family/search',
  path: '/api/family/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFamilySplatRoute = ApiFamilySplatRouteImport.update({
  id: '/api/family/$',
  path: '/api/family/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetSplatRoute = ApiAssetSplatRouteImport.update({
  id: '/api/asset/$',
  path: '/api/asset/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAssetsViewIndexRoute = AppAssetsViewIndexRouteImport.update({
  id: '/assets/view/',
  path: '/assets/view/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsEditIndexRoute = AppAssetsEditIndexRouteImport.update({
  id: '/assets/edit/',
  path: '/assets/edit/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgreementViewIndexRoute = AppAgreementViewIndexRouteImport.update({
  id: '/agreement/view/',
  path: '/agreement/view/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsViewIdRoute = AppAssetsViewIdRouteImport.update({
  id: '/assets/view/$id',
  path: '/assets/view/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsEditIdRoute = AppAssetsEditIdRouteImport.update({
  id: '/assets/edit/$id',
  path: '/assets/edit/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAgreementViewIdRoute = AppAgreementViewIdRouteImport.update({
  id: '/agreement/view/$id',
  path: '/agreement/view/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiUserProfileSplatRoute = ApiUserProfileSplatRouteImport.update({
  id: '/api/user/profile/$',
  path: '/api/user/profile/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/test-upload': typeof TestUploadRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/api/asset/$': typeof ApiAssetSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/family/$': typeof ApiFamilySplatRoute
  '/api/family/search': typeof ApiFamilySearchRoute
  '/api/file/$': typeof ApiFileSplatRoute
  '/api/file/$key': typeof ApiFileKeyRoute
  '/app/agreement/create': typeof AppAgreementCreateRoute
  '/app/assets/add': typeof AppAssetsAddRoute
  '/app/family/add': typeof AppFamilyAddRoute
  '/app/family/edit': typeof AppFamilyEditRoute
  '/app/family/view': typeof AppFamilyViewRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/profile/view': typeof AppProfileViewRoute
  '/api/upload': typeof ApiUploadIndexRoute
  '/app/agreement': typeof AppAgreementIndexRoute
  '/app/assets': typeof AppAssetsIndexRoute
  '/app/family': typeof AppFamilyIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/api/user/profile/$': typeof ApiUserProfileSplatRoute
  '/app/agreement/view/$id': typeof AppAgreementViewIdRoute
  '/app/assets/edit/$id': typeof AppAssetsEditIdRoute
  '/app/assets/view/$id': typeof AppAssetsViewIdRoute
  '/app/agreement/view': typeof AppAgreementViewIndexRoute
  '/app/assets/edit': typeof AppAssetsEditIndexRoute
  '/app/assets/view': typeof AppAssetsViewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/test-upload': typeof TestUploadRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/api/asset/$': typeof ApiAssetSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/family/$': typeof ApiFamilySplatRoute
  '/api/family/search': typeof ApiFamilySearchRoute
  '/api/file/$': typeof ApiFileSplatRoute
  '/api/file/$key': typeof ApiFileKeyRoute
  '/app/agreement/create': typeof AppAgreementCreateRoute
  '/app/assets/add': typeof AppAssetsAddRoute
  '/app/family/add': typeof AppFamilyAddRoute
  '/app/family/edit': typeof AppFamilyEditRoute
  '/app/family/view': typeof AppFamilyViewRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/profile/view': typeof AppProfileViewRoute
  '/api/upload': typeof ApiUploadIndexRoute
  '/app/agreement': typeof AppAgreementIndexRoute
  '/app/assets': typeof AppAssetsIndexRoute
  '/app/family': typeof AppFamilyIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/api/user/profile/$': typeof ApiUserProfileSplatRoute
  '/app/agreement/view/$id': typeof AppAgreementViewIdRoute
  '/app/assets/edit/$id': typeof AppAssetsEditIdRoute
  '/app/assets/view/$id': typeof AppAssetsViewIdRoute
  '/app/agreement/view': typeof AppAgreementViewIndexRoute
  '/app/assets/edit': typeof AppAssetsEditIndexRoute
  '/app/assets/view': typeof AppAssetsViewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/test-upload': typeof TestUploadRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/api/asset/$': typeof ApiAssetSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/family/$': typeof ApiFamilySplatRoute
  '/api/family/search': typeof ApiFamilySearchRoute
  '/api/file/$': typeof ApiFileSplatRoute
  '/api/file/$key': typeof ApiFileKeyRoute
  '/app/agreement/create': typeof AppAgreementCreateRoute
  '/app/assets/add': typeof AppAssetsAddRoute
  '/app/family/add': typeof AppFamilyAddRoute
  '/app/family/edit': typeof AppFamilyEditRoute
  '/app/family/view': typeof AppFamilyViewRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/profile/view': typeof AppProfileViewRoute
  '/api/upload/': typeof ApiUploadIndexRoute
  '/app/agreement/': typeof AppAgreementIndexRoute
  '/app/assets/': typeof AppAssetsIndexRoute
  '/app/family/': typeof AppFamilyIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/api/user/profile/$': typeof ApiUserProfileSplatRoute
  '/app/agreement/view/$id': typeof AppAgreementViewIdRoute
  '/app/assets/edit/$id': typeof AppAssetsEditIdRoute
  '/app/assets/view/$id': typeof AppAssetsViewIdRoute
  '/app/agreement/view/': typeof AppAgreementViewIndexRoute
  '/app/assets/edit/': typeof AppAssetsEditIndexRoute
  '/app/assets/view/': typeof AppAssetsViewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/test-upload'
    | '/app/dashboard'
    | '/api/asset/$'
    | '/api/auth/$'
    | '/api/family/$'
    | '/api/family/search'
    | '/api/file/$'
    | '/api/file/$key'
    | '/app/agreement/create'
    | '/app/assets/add'
    | '/app/family/add'
    | '/app/family/edit'
    | '/app/family/view'
    | '/app/profile/edit'
    | '/app/profile/view'
    | '/api/upload'
    | '/app/agreement'
    | '/app/assets'
    | '/app/family'
    | '/app/profile'
    | '/app/settings'
    | '/api/user/profile/$'
    | '/app/agreement/view/$id'
    | '/app/assets/edit/$id'
    | '/app/assets/view/$id'
    | '/app/agreement/view'
    | '/app/assets/edit'
    | '/app/assets/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/test-upload'
    | '/app/dashboard'
    | '/api/asset/$'
    | '/api/auth/$'
    | '/api/family/$'
    | '/api/family/search'
    | '/api/file/$'
    | '/api/file/$key'
    | '/app/agreement/create'
    | '/app/assets/add'
    | '/app/family/add'
    | '/app/family/edit'
    | '/app/family/view'
    | '/app/profile/edit'
    | '/app/profile/view'
    | '/api/upload'
    | '/app/agreement'
    | '/app/assets'
    | '/app/family'
    | '/app/profile'
    | '/app/settings'
    | '/api/user/profile/$'
    | '/app/agreement/view/$id'
    | '/app/assets/edit/$id'
    | '/app/assets/view/$id'
    | '/app/agreement/view'
    | '/app/assets/edit'
    | '/app/assets/view'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/test-upload'
    | '/app/dashboard'
    | '/api/asset/$'
    | '/api/auth/$'
    | '/api/family/$'
    | '/api/family/search'
    | '/api/file/$'
    | '/api/file/$key'
    | '/app/agreement/create'
    | '/app/assets/add'
    | '/app/family/add'
    | '/app/family/edit'
    | '/app/family/view'
    | '/app/profile/edit'
    | '/app/profile/view'
    | '/api/upload/'
    | '/app/agreement/'
    | '/app/assets/'
    | '/app/family/'
    | '/app/profile/'
    | '/app/settings/'
    | '/api/user/profile/$'
    | '/app/agreement/view/$id'
    | '/app/assets/edit/$id'
    | '/app/assets/view/$id'
    | '/app/agreement/view/'
    | '/app/assets/edit/'
    | '/app/assets/view/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  TestUploadRoute: typeof TestUploadRoute
  ApiAssetSplatRoute: typeof ApiAssetSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFamilySplatRoute: typeof ApiFamilySplatRoute
  ApiFamilySearchRoute: typeof ApiFamilySearchRoute
  ApiFileSplatRoute: typeof ApiFileSplatRoute
  ApiFileKeyRoute: typeof ApiFileKeyRoute
  ApiUploadIndexRoute: typeof ApiUploadIndexRoute
  ApiUserProfileSplatRoute: typeof ApiUserProfileSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-upload': {
      id: '/test-upload'
      path: '/test-upload'
      fullPath: '/test-upload'
      preLoaderRoute: typeof TestUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile/': {
      id: '/app/profile/'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/family/': {
      id: '/app/family/'
      path: '/family'
      fullPath: '/app/family'
      preLoaderRoute: typeof AppFamilyIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assets/': {
      id: '/app/assets/'
      path: '/assets'
      fullPath: '/app/assets'
      preLoaderRoute: typeof AppAssetsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agreement/': {
      id: '/app/agreement/'
      path: '/agreement'
      fullPath: '/app/agreement'
      preLoaderRoute: typeof AppAgreementIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/upload/': {
      id: '/api/upload/'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile/view': {
      id: '/app/profile/view'
      path: '/profile/view'
      fullPath: '/app/profile/view'
      preLoaderRoute: typeof AppProfileViewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile/edit': {
      id: '/app/profile/edit'
      path: '/profile/edit'
      fullPath: '/app/profile/edit'
      preLoaderRoute: typeof AppProfileEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/family/view': {
      id: '/app/family/view'
      path: '/family/view'
      fullPath: '/app/family/view'
      preLoaderRoute: typeof AppFamilyViewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/family/edit': {
      id: '/app/family/edit'
      path: '/family/edit'
      fullPath: '/app/family/edit'
      preLoaderRoute: typeof AppFamilyEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/family/add': {
      id: '/app/family/add'
      path: '/family/add'
      fullPath: '/app/family/add'
      preLoaderRoute: typeof AppFamilyAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assets/add': {
      id: '/app/assets/add'
      path: '/assets/add'
      fullPath: '/app/assets/add'
      preLoaderRoute: typeof AppAssetsAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agreement/create': {
      id: '/app/agreement/create'
      path: '/agreement/create'
      fullPath: '/app/agreement/create'
      preLoaderRoute: typeof AppAgreementCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/file/$key': {
      id: '/api/file/$key'
      path: '/api/file/$key'
      fullPath: '/api/file/$key'
      preLoaderRoute: typeof ApiFileKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file/$': {
      id: '/api/file/$'
      path: '/api/file/$'
      fullPath: '/api/file/$'
      preLoaderRoute: typeof ApiFileSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/family/search': {
      id: '/api/family/search'
      path: '/api/family/search'
      fullPath: '/api/family/search'
      preLoaderRoute: typeof ApiFamilySearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/family/$': {
      id: '/api/family/$'
      path: '/api/family/$'
      fullPath: '/api/family/$'
      preLoaderRoute: typeof ApiFamilySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/asset/$': {
      id: '/api/asset/$'
      path: '/api/asset/$'
      fullPath: '/api/asset/$'
      preLoaderRoute: typeof ApiAssetSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/assets/view/': {
      id: '/app/assets/view/'
      path: '/assets/view'
      fullPath: '/app/assets/view'
      preLoaderRoute: typeof AppAssetsViewIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assets/edit/': {
      id: '/app/assets/edit/'
      path: '/assets/edit'
      fullPath: '/app/assets/edit'
      preLoaderRoute: typeof AppAssetsEditIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agreement/view/': {
      id: '/app/agreement/view/'
      path: '/agreement/view'
      fullPath: '/app/agreement/view'
      preLoaderRoute: typeof AppAgreementViewIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assets/view/$id': {
      id: '/app/assets/view/$id'
      path: '/assets/view/$id'
      fullPath: '/app/assets/view/$id'
      preLoaderRoute: typeof AppAssetsViewIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assets/edit/$id': {
      id: '/app/assets/edit/$id'
      path: '/assets/edit/$id'
      fullPath: '/app/assets/edit/$id'
      preLoaderRoute: typeof AppAssetsEditIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agreement/view/$id': {
      id: '/app/agreement/view/$id'
      path: '/agreement/view/$id'
      fullPath: '/app/agreement/view/$id'
      preLoaderRoute: typeof AppAgreementViewIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/user/profile/$': {
      id: '/api/user/profile/$'
      path: '/api/user/profile/$'
      fullPath: '/api/user/profile/$'
      preLoaderRoute: typeof ApiUserProfileSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppAgreementCreateRoute: typeof AppAgreementCreateRoute
  AppAssetsAddRoute: typeof AppAssetsAddRoute
  AppFamilyAddRoute: typeof AppFamilyAddRoute
  AppFamilyEditRoute: typeof AppFamilyEditRoute
  AppFamilyViewRoute: typeof AppFamilyViewRoute
  AppProfileEditRoute: typeof AppProfileEditRoute
  AppProfileViewRoute: typeof AppProfileViewRoute
  AppAgreementIndexRoute: typeof AppAgreementIndexRoute
  AppAssetsIndexRoute: typeof AppAssetsIndexRoute
  AppFamilyIndexRoute: typeof AppFamilyIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppAgreementViewIdRoute: typeof AppAgreementViewIdRoute
  AppAssetsEditIdRoute: typeof AppAssetsEditIdRoute
  AppAssetsViewIdRoute: typeof AppAssetsViewIdRoute
  AppAgreementViewIndexRoute: typeof AppAgreementViewIndexRoute
  AppAssetsEditIndexRoute: typeof AppAssetsEditIndexRoute
  AppAssetsViewIndexRoute: typeof AppAssetsViewIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppAgreementCreateRoute: AppAgreementCreateRoute,
  AppAssetsAddRoute: AppAssetsAddRoute,
  AppFamilyAddRoute: AppFamilyAddRoute,
  AppFamilyEditRoute: AppFamilyEditRoute,
  AppFamilyViewRoute: AppFamilyViewRoute,
  AppProfileEditRoute: AppProfileEditRoute,
  AppProfileViewRoute: AppProfileViewRoute,
  AppAgreementIndexRoute: AppAgreementIndexRoute,
  AppAssetsIndexRoute: AppAssetsIndexRoute,
  AppFamilyIndexRoute: AppFamilyIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppAgreementViewIdRoute: AppAgreementViewIdRoute,
  AppAssetsEditIdRoute: AppAssetsEditIdRoute,
  AppAssetsViewIdRoute: AppAssetsViewIdRoute,
  AppAgreementViewIndexRoute: AppAgreementViewIndexRoute,
  AppAssetsEditIndexRoute: AppAssetsEditIndexRoute,
  AppAssetsViewIndexRoute: AppAssetsViewIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  TestUploadRoute: TestUploadRoute,
  ApiAssetSplatRoute: ApiAssetSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFamilySplatRoute: ApiFamilySplatRoute,
  ApiFamilySearchRoute: ApiFamilySearchRoute,
  ApiFileSplatRoute: ApiFileSplatRoute,
  ApiFileKeyRoute: ApiFileKeyRoute,
  ApiUploadIndexRoute: ApiUploadIndexRoute,
  ApiUserProfileSplatRoute: ApiUserProfileSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
